In [ ]:
alphabets='ABCDEFGHIJKLMNOPQRSTUVWXYZ'


In [ ]:
list(enumerate(alphabets))

[(0, 'A'),
 (1, 'B'),
 (2, 'C'),
 (3, 'D'),
 (4, 'E'),
 (5, 'F'),
 (6, 'G'),
 (7, 'H'),
 (8, 'I'),
 (9, 'J'),
 (10, 'K'),
 (11, 'L'),
 (12, 'M'),
 (13, 'N'),
 (14, 'O'),
 (15, 'P'),
 (16, 'Q'),
 (17, 'R'),
 (18, 'S'),
 (19, 'T'),
 (20, 'U'),
 (21, 'V'),
 (22, 'W'),
 (23, 'X'),
 (24, 'Y'),
 (25, 'Z')]

In [ ]:
int_to_char=dict(enumerate(alphabets))
int_to_char

{0: 'A',
 1: 'B',
 2: 'C',
 3: 'D',
 4: 'E',
 5: 'F',
 6: 'G',
 7: 'H',
 8: 'I',
 9: 'J',
 10: 'K',
 11: 'L',
 12: 'M',
 13: 'N',
 14: 'O',
 15: 'P',
 16: 'Q',
 17: 'R',
 18: 'S',
 19: 'T',
 20: 'U',
 21: 'V',
 22: 'W',
 23: 'X',
 24: 'Y',
 25: 'Z'}

In [ ]:
#convert char to int
char_to_int={v:k for k,v in int_to_char.items()} #using dictionary comperhension
char_to_int

{'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'J': 9,
 'K': 10,
 'L': 11,
 'M': 12,
 'N': 13,
 'O': 14,
 'P': 15,
 'Q': 16,
 'R': 17,
 'S': 18,
 'T': 19,
 'U': 20,
 'V': 21,
 'W': 22,
 'X': 23,
 'Y': 24,
 'Z': 25}

#### Data Preparation

In [ ]:
seq_length = 1
x = []
y = []
for i in range(len(alphabets)-seq_length):
  seq_in = [alphabets[i]]
  seq_out = alphabets[i+1]
  x += [[char_to_int[seq_in[0]]]]
  y += [char_to_int[seq_out]]
  print(seq_in, '->', seq_out)

['A'] -> B
['B'] -> C
['C'] -> D
['D'] -> E
['E'] -> F
['F'] -> G
['G'] -> H
['H'] -> I
['I'] -> J
['J'] -> K
['K'] -> L
['L'] -> M
['M'] -> N
['N'] -> O
['O'] -> P
['P'] -> Q
['Q'] -> R
['R'] -> S
['S'] -> T
['T'] -> U
['U'] -> V
['V'] -> W
['W'] -> X
['X'] -> Y
['Y'] -> Z


Prepare the output variable

In [ ]:
from keras.utils import to_categorical
y_new = to_categorical(y)  ##one hot encoded format
y_new

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 

In [ ]:
import numpy as np

In [ ]:
x = np.reshape(x, (25,1,1)) #total no. of words = 1 and length of words = 1

In [ ]:
x

array([[[ 0]],

       [[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]],

       [[12]],

       [[13]],

       [[14]],

       [[15]],

       [[16]],

       [[17]],

       [[18]],

       [[19]],

       [[20]],

       [[21]],

       [[22]],

       [[23]],

       [[24]]])

In [ ]:
x.shape

(25, 1, 1)

In [ ]:
x_new = x/25.0 #Normalizing the data
x_new

array([[[0.  ]],

       [[0.04]],

       [[0.08]],

       [[0.12]],

       [[0.16]],

       [[0.2 ]],

       [[0.24]],

       [[0.28]],

       [[0.32]],

       [[0.36]],

       [[0.4 ]],

       [[0.44]],

       [[0.48]],

       [[0.52]],

       [[0.56]],

       [[0.6 ]],

       [[0.64]],

       [[0.68]],

       [[0.72]],

       [[0.76]],

       [[0.8 ]],

       [[0.84]],

       [[0.88]],

       [[0.92]],

       [[0.96]]])

Create the model

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, LSTM

In [ ]:
model = Sequential()

model.add(Dense(25, input_shape=(1,1), activation='relu'))
model.add(LSTM(32))
model.add(Dense(26, activation='softmax'))

In [ ]:
model.compile(loss= 'categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

Model training

In [ ]:
model.fit(x_new, y_new, epochs=1000, batch_size=1)

Epoch 1/1000
25/25 [==============================] - 3s 3ms/step - loss: 3.2660 - accuracy: 0.0400
Epoch 2/1000
25/25 [==============================] - 0s 3ms/step - loss: 3.2567 - accuracy: 0.0400
Epoch 3/1000
25/25 [==============================] - 0s 3ms/step - loss: 3.2524 - accuracy: 0.0400
Epoch 4/1000
25/25 [==============================] - 0s 3ms/step - loss: 3.2472 - accuracy: 0.0400
Epoch 5/1000
25/25 [==============================] - 0s 3ms/step - loss: 3.2428 - accuracy: 0.0400
Epoch 6/1000
25/25 [==============================] - 0s 4ms/step - loss: 3.2355 - accuracy: 0.0400
Epoch 7/1000
25/25 [==============================] - 0s 3ms/step - loss: 3.2275 - accuracy: 0.0400
Epoch 8/1000
25/25 [==============================] - 0s 3ms/step - loss: 3.2178 - accuracy: 0.0400
Epoch 9/1000
25/25 [==============================] - 0s 3ms/step - loss: 3.2068 - accuracy: 0.0400
Epoch 10/1000
25/25 [==============================] - 0s 3ms/step - loss: 3.1913 - accuracy: 0.0400

In [ ]:
# evaluate this model on test data, pass the whole data
loss, acc = model.evaluate(x_new, y_new, batch_size=1)
#print the loss and accuracy
print('Test Loss: %f' % (loss))
print('Test Accuracy: %f' % (acc))

25/25 [==============================] - 0s 2ms/step - loss: 0.3974 - accuracy: 1.0000
Test Loss: 0.397422
Test Accuracy: 1.000000


Predict the character in sequence

In [ ]:
new = 'K'
new_int = [char_to_int[new]]
new_x = np.reshape(new_int, (1,1,1))
new_x = new_x/25.0

In [ ]:
#predict the next character
yhat = model.predict(new_x)
# int_to_char
int_to_char[np.argmax(yhat)]

1/1 [==============================] - 0s 27ms/step


'L'

In [ ]:
seq_length = 3
x = []
y = []
for i in range(len(alphabets)-seq_length):
  seq_in = alphabets[i: (i + seq_length)]
  seq_out = alphabets[i+ seq_length]
  x.append([char_to_int[char] for char in seq_in])
  y.append([char_to_int[seq_out]])
  print(seq_in, '->', seq_out)

ABC -> D
BCD -> E
CDE -> F
DEF -> G
EFG -> H
FGH -> I
GHI -> J
HIJ -> K
IJK -> L
JKL -> M
KLM -> N
LMN -> O
MNO -> P
NOP -> Q
OPQ -> R
PQR -> S
QRS -> T
RST -> U
STU -> V
TUV -> W
UVW -> X
VWX -> Y
WXY -> Z


In [ ]:
x = np.reshape(x, (len(x),seq_length,1)) #total no. of words = 1 and length of words = 1

In [ ]:
x.shape

(23, 3, 1)

In [ ]:
y_new = to_categorical(y)  ##one hot encoded format
y_new

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 

In [ ]:
x=x/25.0

In [ ]:
# xtrain = x[:21]
# xtest = x[21:]
# ytrain = y_new[:21]
# ytest = y_new[21:]

In [ ]:
# #print shapes
# print(xtrain.shape)
# print(xtest.shape)
# print(ytrain.shape)
# print(ytest.shape)

(21, 3, 1)
(2, 3, 1)
(21, 26)
(2, 26)


In [ ]:
# #create a model for  x_train
# model1 = Sequential()

# model1.add(Dense(25, input_shape=(3,1), activation='relu'))
# model1.add(LSTM(128))
# model1.add(Dense(26, activation='softmax'))

In [ ]:
model = Sequential()

model.add(Dense(25, input_shape=(3,1), activation='relu'))
model.add(LSTM(128))
model.add(Dense(26, activation='softmax'))

In [ ]:
model.compile(loss= 'categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.fit(x, y_new, epochs=1000, batch_size=1)

Epoch 1/1000
23/23 [==============================] - 3s 5ms/step - loss: 3.2815 - accuracy: 0.0000e+00
Epoch 2/1000
23/23 [==============================] - 0s 4ms/step - loss: 3.2469 - accuracy: 0.0435
Epoch 3/1000
23/23 [==============================] - 0s 6ms/step - loss: 3.2291 - accuracy: 0.0435
Epoch 4/1000
23/23 [==============================] - 0s 5ms/step - loss: 3.1990 - accuracy: 0.0435
Epoch 5/1000
23/23 [==============================] - 0s 5ms/step - loss: 3.1694 - accuracy: 0.0435
Epoch 6/1000
23/23 [==============================] - 0s 4ms/step - loss: 3.1169 - accuracy: 0.0435
Epoch 7/1000
23/23 [==============================] - 0s 5ms/step - loss: 3.0684 - accuracy: 0.0435
Epoch 8/1000
23/23 [==============================] - 0s 6ms/step - loss: 3.0377 - accuracy: 0.0000e+00
Epoch 9/1000
23/23 [==============================] - 0s 6ms/step - loss: 2.9959 - accuracy: 0.0870
Epoch 10/1000
23/23 [==============================] - 0s 5ms/step - loss: 2.9554 - accuracy

In [ ]:
#accuracy
loss, acc = model.evaluate(x, y_new, batch_size=1)
#print the loss and accuracy
print('Test Loss: %f' % (loss))
print('Test Accuracy: %f' % (acc))

23/23 [==============================] - 1s 3ms/step - loss: 0.0184 - accuracy: 1.0000
Test Loss: 0.018363
Test Accuracy: 1.000000


In [ ]:
new = 'WXY'
new_int = [char_to_int[char] for char in new]
new_x = np.reshape(new_int, (1,3,1))
new_x = new_x/25.0

In [ ]:
#predict the next character
yhat = model.predict(new_x)
# int_to_char
int_to_char[np.argmax(yhat)]

1/1 [==============================] - 0s 29ms/step


'Z'