In [ ]:
# pip install transformers

In [ ]:
import tensorflow as tf
from transformers import BertTokenizer, TFBertForSequenceClassification

In [ ]:
# Load pretrained  model and tokenizer
model_name = "bert-base-uncased"
tokenizer = BertTokenizer.from_pretrained(model_name)
model = TFBertForSequenceClassification.from_pretrained(model_name, num_labels=2) #labels means categories to be classified, in this case we have positive and negative

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
# Define the text we want to classify
texts = ["This was an amazing very beautiful product.", "This is a very nice product"]

In [ ]:
# Tokenize the text
inputs = tokenizer(texts, padding=True, truncation=True, return_tensors="tf", max_length=80)

In [ ]:
#Get the model's predictions
outputs = model(**inputs)
logits = outputs.logits
logits

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.0420322 , -0.05664636],
       [ 0.2307871 , -0.3090959 ]], dtype=float32)>

In [ ]:
predictions = tf.nn.softmax(logits, axis=-1)

In [ ]:
np.array(predictions)

array([[0.5246496 , 0.47535032],
       [0.6317852 , 0.3682148 ]], dtype=float32)

In [ ]:
predictions = ['Positive','Negative']
for text, prediction in zip(texts, predictions):
    print(f"Text: {text}")
    print(f"Prediction: {prediction}")
    print()

Text: This was an amazing very beautiful product.
Prediction: Positive

Text: This is a very nice product
Prediction: Negative

